sudo: false
language: node_js
node_js:
  - "8"
# To compile native modules for io.js v3 or Node.js v4 or later,
# a C++11 standard-compliant compiler is required.
# More specifically,
# either gcc 4.8 (or later), or clang 3.5 (or later) works.
# AWS EB environment use gcc 4.8
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Node.js-v4-(or-io.js-v3)-compiler-requirements
env:
  global:
    - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
install:
  - npm install

# greenkeeper update npm lockfile
before_install:
- npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

script:
  - npm run lint && npm run flow
  - npm run test
  - npm run test -- --coverage
  - npm run build && npm --silent run analyze -- --html > bundle-analysis.log.html
