sudo: false
language: node_js
node_js:
  - "8"
# To compile native modules for io.js v3 or Node.js v4 or later,
# a C++11 standard-compliant compiler is required.
# More specifically,
# either gcc 4.8 (or later), or clang 3.5 (or later) works.
# AWS EB environment use gcc 4.8
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Node.js-v4-(or-io.js-v3)-compiler-requirements
env:
  global:
    - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
install:
  - npm i -g npm@6
  - npm ci

# greenkeeper update npm lockfile
before_install:
  - npm install -g greenkeeper-lockfile@1
  - greenkeeper-lockfile-update
after_success:
  - greenkeeper-lockfile-upload
  - bash <(curl -s https://codecov.io/bash)
  - mv coverage analysis build && npm run deploy:ci

script:
  - npm run lint && npm run flow
  - npm run test -- --coverage
  - npm run build && npm run analyze:ci
