# Javascript Node CircleCI 2.0 configuration file
defaults: &defaults
  docker:
    - image: circleci/node:8.11
  working_directory: ~/repo
version: 2
jobs:
  checkout_code:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - source-{{ .Branch }}-{{ .Revision }}
            - source-{{ .Branch }}-
            - source-

      - checkout

      - save_cache:
          key: source-{{ .Branch }}-{{ .Revision }}
          paths:
            - "~/repo"

  install_dependencies:
    <<: *defaults
    steps:
      - restore_cache:
          key: source-{{ .Branch }}-{{ .Revision }}
      - restore_cache:
          keys:
            - depens-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
            - depens-{{ checksum "package.json" }}
            - depens-
      - run: sudo npm i -g npm@6
      - run: npm ci
      - save_cache:
          paths:
            - node_modules
          key: depens-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
  lint:
    <<: *defaults
    steps:
      - restore_cache:
          key: source-{{ .Branch }}-{{ .Revision }}
      - restore_cache:
          key: depens-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
      - run: npm run lint && npm run flow
  test:
    <<: *defaults
    steps:
      - restore_cache:
          key: source-{{ .Branch }}-{{ .Revision }}
      - restore_cache:
          key: depens-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
      - run: npm run test:coverage
      - persist_to_workspace:
          root: ~/repo
          paths:
            - coverage
  build:
    <<: *defaults
    steps:
      - restore_cache:
          key: source-{{ .Branch }}-{{ .Revision }}
      - restore_cache:
          key: depens-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}

      - run: npm run build

      - persist_to_workspace:
          root: ~/repo
          paths:
            - build
            - package.json
            - package-lock.json
  analyze:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          key: depens-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
      - run: npm run analyze:ci
      - store_artifacts:
          path: bundle-analysis.html
          destination: bundle-analysize.html
      - persist_to_workspace:
          root: ~/repo
          paths:
            - bundle-analysis.html
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          key: depens-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
      - run: cp coverage bundle-analysis.html -r build && npm run deploy:ci
workflows:
  version: 2
  ci_cd:
    jobs:
      - checkout_code
      - install_dependencies:
          requires:
            - checkout_code
      - lint:
          requires:
            - install_dependencies
      - test:
          requires:
            - install_dependencies
      - build:
          requires:
            - lint
            - test
      - analyze:
          requires:
            - build
      - deploy:
          requires:
            - analyze
          filters:
            branches:
              only:
                - master
