# Javascript Node CircleCI 2.0 configuration file
defaults: &defaults
  docker:
    - image: circleci/node:8.11
  working_directory: ~/repo

version: 2
jobs:
  install_dependencies:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - depens-{{ checksum "package.json" }}
            - depens-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: depens-{{ checksum "package.json" }}

  lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: depens-{{ checksum "package.json" }}

      - run: npm run lint && npm run flow

  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: depens-{{ checksum "package.json" }}

      - run: npm run test

  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: depens-{{ checksum "package.json" }}

      - run: npm run build

      - persist_to_workspace:
          root: ~/repo
          paths:
            - build

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo/build

      # modify below others like run aws deploy cmd or scp files to a ftp server
      - store_artifacts:
          path: ~/repo/build
          destination: prod-dist

  deploy_dev:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo/build

      # modify below others like run aws deploy cmd or scp files to a ftp server
      - store_artifacts:
          path: ~/repo/build
          destination: dev-dist

  analyze:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: depens-{{ checksum "package.json" }}
      - attach_workspace:
          at: ~/repo/build

      - run: npm --silent run analyze -- --html > bundle-analysis.log.html

      - store_artifacts:
          path: /tmp/artifact-1
          destination: bundle-analysize.html

  coverage:
    <<: *defaults
    steps:
      - restore_cache:
          key: source-{{ .Branch }}-{{ .Revision }}
      - restore_cache:
          key: depens-{{ checksum "package.json" }}

      - run: npm run test -- --coverage

workflows:
  version: 2
  lint_and_flow:
    jobs:
      - install_dependencies:
          requires:
            - checkout_code
      - lint:
          requires:
            - install_dependencies
      - test:
          requires:
            - install_dependencies
